version: "3.8"
networks:
  chatnetwork:
    driver: bridge
services:
  kam-app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kameleoon
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - chatnetwork

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=kameleoon
    ports:
      - "5432:5432"
    networks:
      - chatnetwork